#ifndef BANK_CONFIG_H_INCLUDED
#define BANK_CONFIG_H_INCLUDED

#define NUMBER_OF_CUSTOMERS     10

#define MAX_RANDOM_PASSWORD     9999
#define MIN_RANDOM_PASSWORD     0
#define RANDOM_PASSWORD_LENGTH  4

#define ADMIN_USERNAME              "Admin"
#define ADMIN_PASSWORD_LENGTH       4
#define ADMIN_PASSWORD              "1234"



#endif // BANK_CONFIG_H_INCLUDED
